apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2 # Dwie repliki aplikacji
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: my-python-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis"
