name: Application Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      REDIS_HOST: redis

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install redis

      - name: Wait for Redis to be ready
        run: |
          for i in {1..10}; do
            if echo PING | nc -w 1 redis 6379; then
              echo "Redis is ready!"
              exit 0
            fi
            echo "Waiting for Redis..."
            sleep 2
          done
          echo "Redis did not start in time"
          exit 1

      - name: Run application test
        run: python hello.py
