name: Application Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      REDIS_HOST: redis

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install redis

      - name: Debug - List running services
        run: docker ps -a

      - name: Debug - Check Redis connectivity
        run: |
          for i in {1..10}; do
              echo "Checking Redis connection..."
              if docker run --rm --network=host redis redis-cli -h 127.0.0.1 ping; then
            echo "Redis is responding!"
            exit 0
          fi
          echo "Redis not ready, retrying..."
            sleep 2
          done
          echo "Redis did not start in time"
          exit 1

      - name: Run application test in Docker
        run: |
          docker run --rm --network=host -v $(pwd):/app -w /app python:3.9 \
          bash -c "pip install redis && python hello.py"
